package com.luxpmsoft.luxaipoc.api

object ConstantAPI {
//    var BASE_URL = "https://59.160.80.73/"
    const val UPLOAD_FILE = "upload2.php"
//    var BASE_URL = "http://18.191.201.33:8000/"
    var BASE_URL = "http://63.135.169.171:8000/"
    var URL_VIDEO = "http://207.254.60.225:8000/"
//    var AR_BASE_URL = "http://18.116.105.225/"
    var AR_BASE_URL = "http://18.117.60.53/"
    var BODY_URL = "http://35.202.70.204:8000/"
//    var OPEN_AIR_BASE_URL = "https://prod-openairapi.luxpmsoft.com/api/v1/"
    const val ALL_MODELS = "allmodels"
    const val VIEW_MODELS = "viewmodel"
    const val GET_THUMBNAIL = "get_thumbnail_url"
    const val REQUEST_SESSION = "request_session"
    const val UPLOAD_PHOTO = "upload_photo"
    const val MULTI_UPLOAD_PHOTO = "multi_upload_photo"
    const val MULTI_UPLOAD_VIDEO = "multi_upload_video"
    const val FINISH_PHOTO_UPLOAD = "finish_photo_upload"
    const val UPLOAD_FILE_ZIP = "upload"
    /*====*/
    const val RENAME_MODEL = "rename_session"
    const val GET_MODEL_URL = "get_model_url"
    const val GET_MODEL = "getmodel"
    var USER_ID = ""

    /*open air====*/
    const val LOGIN = "auth/login/manual"
    const val ME = "auth/me"
    const val SUBSCRIPTION_USER = "user/subscription"
    const val SUBSCRIPTION = "subscription"
    const val SUBSCRIPTION_TYPE = "subscription/type"
    const val RECONSTRUCTION = "reconstruction"
    const val CAD_FILE = "cad-file/board/{boardId}"
    const val CAD_FILE_DETAIL = "cad-file/{id}"
    const val CAD_FILE_ADD = "cad-file/add"
    const val CAD_FILE_SAVE = "cad-file/{cadFileId}/save"
    const val RECONSTRUCTION_HTML = "reconstruction/cadfile/html/{id}"
    const val THUMBNAIL = "reconstruction/image"
    const val MODELS = "reconstruction/model/{reconstructionID}"
    const val USER_DETAIL = "user/details"
    const val USER_IMAGE = "user/image"
    const val COMMENT_ADD = "comments/add"
    const val COMMENT_GET = "comments/{commentId}"
    const val SEND_OTP = "user/register/phone/send-otp"
    const val REGISTER = "user/register"
    const val EMAIL_VERIFICATION = "user/emailVerification-link"
    const val RESET_SEND_OTP = "user/phone/resetPassword/send-otp"
    const val VERIFY_OTP = "user/phone/resetPassword/verify-otp"
    const val RESET_PASSWORD = "auth/reset-password"
    const val CHANGE_PASSWORD = "auth/change-password"
    const val FORGET_PASSWORD = "auth/forget-password/email"
    const val LOGIN_SNS = "auth/login/mobile/sns"
    const val DASHBOARD = "organization/dashboard/{organizationId}"
    const val ORGANIZATION_REPOSITORIES = "organization/details/{organizationId}/get"
    const val ORGANIZATION_WORKSPACE = "repository/{repositoryId}/workspacelist/get"
    const val ORGANIZATION_PROJECT_BOARD = "workspace/{workspaceId}/get"
    const val ORGANIZATION_CREATE = "organization/create"
    const val ORGANIZATION_CHECK = "organization/check"
    const val ORGANIZATION_JOIN_REQUEST = "organization/join/request"
    const val ORGANIZATION_DETAIL = "organization/details/{organizationId}/users/get"
    const val USER_REPOSITORY = "repository/{repositoryId}/users"
    const val CREATE_REPOSITORY = "repository/create"
    const val CREATE_WORKSPACE = "workspace/add"
    const val DELETE_WORKSPACE = "workspace/{organizationId}/{workspaceId}/delete"
    const val EDIT_WORKSPACE = "workspace/{workspaceId}/rename"
    const val CREATE_PROJECT = "folder/{workspaceId}/add"
    const val CREATE_BOARD = "repository/workspace/folder/board/{workspaceFolderId}/add"
    const val DELETE_PROJECT = "folder/{folderId}/delete"
    const val DELETE_BOARD = "repository/workspace/folder/board/{boardId}/delete"
    const val NOTIFICATION = "notification"
    const val TAG_EDIT = "tags/{tagId}"
    const val TAG_ADD = "tags/add"
    const val COMMENT_TAG_ADD = "comments/{commentId}/tags/{tagId}"
    const val GET_ORGANIZATION_BY_NAME = "organization/check/partial"

    //
    const val CREATE_SESSION = "create_session"
    const val UPLOAD_VIDEO = "upload_video"
    const val DOWNLOAD_SESSION = "download/{session_id}"
    const val BODY_POSE = "bodypose/predict"

    //new
    const val REMOVE_REPOSITORIES = "repository/{repositoryId}/remove"
    const val UPDATE_REPOSITORIES = "repository/{repositoryId}/update"
    const val PHOTO_UPDATE_REPOSITORIES = "repository/{repositoryId}/photo/update"
    const val DELETE_USER = "repository/{organizationId}/{repositoryUserId}/removeuser"
    const val ADD_USER = "repository/{repositoryId}/adduser"
    const val SERVICE_UPLOAD = "service/upload"

    //defect detect
    const val DEFECT_GET_MODEL = "get_model/{userId}"
    const val TEST_DETECTION = "test_detection/multiple/new"
    const val INCREASE_DATASET = "increase_dataset"
    const val GENERATE_SESSION = "generate_session"
    const val RETRAIN_PROCESS = "retrain_process"
    const val GET_TESTED_MODELS = "get_tested_models/{user_id}"

    //
    const val WORKOUT_VIDEO = "exercise/video_upload"
    const val GET_EXERCISE_VIDEOS = "exercise/get_exercise_videos"
    const val GET_EXERCISE_CATEGORY = "exercise/category"
    const val DOWNLOAD_ZIP = "download/img"
}